services:
  tor:
    build: ./tor
    container_name: tor
    restart: unless-stopped
    # Remove user to run as root inside container
    networks:
      - tor-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
      - /var/lib/tor
    ports:
      - "127.0.0.1:9050:9050"
    dns:
      - 1.1.1.1
      - 8.8.8.8

  bitcoin-knots:
    build:
      context: ./bitcoin-knots
    container_name: bitcoin-knots
    restart: unless-stopped
    user: "bitcoin"
    depends_on:
      - tor
    volumes:
      - bitcoin_data:/bitcoin
      - cookie_share:/cookie:rw
    networks:
      - tor-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

networks:
  tor-net:

volumes:
  bitcoin_data:
  tor-data:
  cookie_share:
