services:
  tor:
    image: alpine:latest
    container_name: tor
    command: >
      sh -c "apk add --no-cache tor && tor -f /etc/tor/torrc"
    volumes:
      - ./tor/torrc:/etc/tor/torrc:ro
      - tor-data:/var/lib/tor:rw
    networks:
      - tor-net
    ports:
      - "127.0.0.1:9050:9050"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

  bitcoin-knots:
    image: bitcoinknots/bitcoinknots:0.21.0.knots20211127
    container_name: bitcoin-knots
    depends_on:
      - tor
    command: >
      -proxy=tor:9050
      -onlynet=onion
      -listen=1
      -listenonion=1
      -txindex=1
      -server=1
      -conf=/bitcoin/.bitcoin/bitcoin.conf
      -datadir=/bitcoin/.bitcoin
    volumes:
      - bitcoin_data:/bitcoin
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf:ro
    networks:
      - tor-net
    user: "1000:1000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp

networks:
  tor-net:
    internal: true

volumes:
  bitcoin_data:
  tor-data:
