services:
  tor:
    build: ./tor
    container_name: tor
    restart: unless-stopped
    ports:
      - "9050:9050"
    networks:
      - tor-net
    dns:
      - 1.1.1.1
      - 8.8.8.8

  bitcoin-knots:
    build: ./bitcoin-knots
    container_name: bitcoin-knots
    restart: unless-stopped
    depends_on:
      - tor
    networks:
      - tor-net
    volumes:
      - bitcoin_data:/bitcoin
      - cookie_share:/cookie
    entrypoint: /wait-for-tor.sh

volumes:
  bitcoin_data:
  cookie_share:

networks:
  tor-net:
    name: tor-net
    driver: bridge
