services:
  tor:
    image: alpine:latest
    container_name: tor
    restart: unless-stopped
    command: >
      sh -c "apk add --no-cache tor &&
             tor -f /etc/tor/torrc"
    volumes:
      - /volume1/docker/tor-data:/var/lib/tor:rw
      - ./tor/torrc:/etc/tor/torrc:ro
    networks:
      - tor-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "127.0.0.1:9050:9050"

  bitcoin-knots:
    image: kylemanna/bitcoind:latest
    container_name: bitcoin-knots
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      - tor
    volumes:
      - /volume1/docker/bitcoin_data:/bitcoin
      - /volume1/docker/cookie:/cookie
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf:ro
    environment:
      - BITCOIN_EXTRA_ARGS=-proxy=tor:9050
    networks:
      - tor-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: false
    tmpfs:
      - /tmp

networks:
  tor-net:
    driver: bridge
    internal: false
